# Spring
server:
  port: 8080
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
spring:
  main:
    banner-mode: console
    lazy-initialization: true
---
# R2DBC
spring:
  r2dbc:
    show-sql: true
    url: r2dbc:pool:mysql://localhost:3306/mcmovies
    username: ${DB_USER:camilo}
    password: ${DB_PASSWORD:Yo5817282/}
---
# Logging
logging:
  level:
    root: info
---
# Jwt
jwt:
  secret: EPzuE1fY/zKURZ0eklR27ULNZTpAO51+dfDWt3iJRI7zyv+UdDjXaDlkV7X1I04r89mvdet5CAWSFkfrKv+fmg==
  expiration: 3600000
